version: "3.3"
services:
  frontend:
    build: ./frontend
    container_name: hrsfc-time-frontend
    env_file:
      - ./config/frontend.env
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: hrsfc-time-backend
    env_file:
      - ./config/backend.env
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: unless-stopped

  # database
  mongodb:
    image: mongo:6
    container_name: mongodb
    env_file:
     - ./config/mongodb.env
    volumes:
    # - mongodb-data:/data/db
    # - ./config/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
     - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
     - "27017:27017"
    restart: unless-stopped

  # ngnix for entrypoint
  proxy:
    image: nginx:1.19
    volumes:
      - "./config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf"
    links:
      - frontend
      - backend
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

# persistent data
volumes:
  mongodb-data:
  uploads-data:
